name: CI

on: [push]

jobs:
  qa:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.9]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm test
        